#!/usr/bin/env ansible-playbook
#
# This playbook builds an image and makes it available to all nodes in
# the cluster. It does so by buidling the image on all nodes and importing
# it to the local image store on each node.

# This allows us to make a custom image available to Kubernetes, without having
# to push it to any registry.
#
# Such images can be used in places where an `image` definition is used,
# given that the `imagePullPolicy` is set to `IfNotPresent`. Note that this
# does not work with the `latest` label though, which is always pulled.
#
- name: Build Image
  hosts: nodes
  gather_facts: false
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
    - name: Sync Dockerfile directory
      synchronize:
        src: "{{ dockerfile | dirname | realpath }}/"
        dest: /tmp/build-image
        mode: push
        recursive: true
        delete: true
        times: true
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.github"
          - "--exclude=k8test"
          - "--exclude=venv"

    - name: Build image
      command: >
        nerdctl build . --namespace k8s.io -t '{{ tag }}' {{ extra }}
      args:
        chdir: /tmp/build-image
