#!/usr/bin/env ansible-playbook
#
# This playbook deletes a previously created cluster and deletes the files
# associated with it.
#
- name: Delete Cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set optional variables
      set_fact:
        cluster_prefix: '{{ cluster_prefix | default("k8test") }}'

    - name: Destroy servers
      cloudscale_ch.cloud.server:
        name: '{{ item }}'
        state: absent
      changed_when: true
      loop: "{{ groups['nodes'] | default([]) }}"

    - name: Destroy private network
      cloudscale_ch.cloud.network:
        name: '{{ cluster_prefix }}-private-network'
        state: absent

    - name: Remove kubeconfig
      file:
        dest: '{{ playbook_dir }}/../cluster/admin.conf'
        state: absent

    - name: Remove inventory
      file:
        dest: '{{ playbook_dir }}/../cluster/inventory.yml'
        state: absent
