#!/usr/bin/env ansible-playbook
#
# This playbook imports an image from the host and makes it available to
# all nodes in the cluster.
#
# This allows us to make a custom image available to Kubernetes, without having
# to push it to any registry.
#
# Such images can be used in places where an `image` definition is used,
# given that the `imagePullPolicy` is set to `IfNotPresent`. Note that this
# does not work with the `latest` label though, which is always pulled.
#
- name: Import Image
  hosts: nodes
  gather_facts: false
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
    - name: Upload the image
      copy:
        src: "{{ image }}"
        dest: "/tmp/{{ image | basename }}"
        force: true

    - name: Import the image
      command: 'nerdctl load --namespace k8s.io -i "/tmp/{{ image | basename }}"'
