#!/usr/bin/env ansible-playbook
#
# This playbook imports a container from the host and makes it available to
# all nodes in the cluster. For this to work, it installs podman on each node.
#
# Since podman shares its underlying storage with CRI-O, this allows us to
# make a custom container available to Kubernetes, without having to push it
# top any registry.
#
# Such containers can be used in places where an `image` definition is used,
# given that the `imagePullPolicy` is set to `IfNotPresent`. Note that this
# does not work with the `latest` label though, which is always pulled.
#
- name: Import Image
  hosts: nodes
  gather_facts: false
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
    - name: Ensure podman is installed
      package:
        name: podman

    - name: Upload the image
      copy:
        src: "{{ image }}"
        dest: "/tmp/{{ image | basename }}"
        force: true

    - name: Import the image
      command: 'podman load -i "/tmp/{{ image | basename }}"'
