#!/usr/bin/env ansible-playbook
#
# This playbook updates the cloudscale cluster secrets in the given cluster.
#
- name: Update Secrets
  hosts: controls[0]
  gather_facts: false
  become: true
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
    - name: Store secrets
      copy:
        content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloudscale
            namespace: kube-system
          stringData:
            access-token: "{{ lookup('env', 'CLOUDSCALE_API_TOKEN') }}"
        dest: /tmp/cloudscale-secret
        mode: 0600

    - name: Delete existing secret
      shell: kubectl -n kube-system delete secret cloudscale || true

    - name: Create secret
      shell: kubectl create -f /tmp/cloudscale-secret
